name: 投诉评论
description: 遇到不合适的评论？在这里进行举报
title: "[投诉评论]: "
labels: ["投诉评论"]
assignees: 
  - zjuchalaoshi
body:
  - type: markdown
    attributes:
      value: |
        请填写以下信息：
  - type: input
    id: url
    attributes:
      label: 投诉页面链接
      description: 请粘贴投诉页面的链接
      placeholder: https://chalaoshi.de/t/xxx
    validations:
      required: true

